<?xml version="1.0" encoding="utf-8"?><Database Name="DataSet" Class="DataWorkerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\DataSet.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="TheTime.Properties.Settings" SettingsPropertyName="DataSetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OWMForecast" Member="OWMForecasts">
    <Type Name="OWMForecast">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="region" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="period" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="precipitation" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="windDirection" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="windSpeed" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="temperature" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="pressure" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="humidity" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="clouds" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="symbol" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppSettings" Member="AppSettings">
    <Type Name="AppSetting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="service" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="curCity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="curRegion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="curCountry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="forecastDaysCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>